name: OAS Generator

on:
  workflow_dispatch:

env:
  TARGET_REPO: team-moeum/checkmate-frontend
  TARGET_BRANCH: main
  SOURCE_BRANCH: oas-${{ github.run_number }}-${{ github.run_attempt }}
  API_DOCS_URL: ${{ secrets.API_DOCS_URL }}
  PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

jobs:
  generate-swagger:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Get Swagger JSON
        run: |
          curl -f ${{ env.API_DOCS_URL }} > swagger.json
          if [ ! -s swagger.json ]; then
            echo "Failed to retrieve swagger.json"
            exit 1
          fi
          echo "Successfully retrieved swagger.json"

      - name: Checkout target repository
        uses: actions/checkout@v4
        with:
          repository: ${{ env.TARGET_REPO }}
          token: ${{ env.PERSONAL_ACCESS_TOKEN }}
          path: target-repo

      - name: Create Pull Request
        run: |
          cd target-repo
          git config --local user.email "moeum[bot]@users.noreply.github.com"
          git config --local user.name "moeum[bot]"

          git checkout -b ${{ env.SOURCE_BRANCH }}
          cp ../swagger.json ./docs/api-doc.json
          git add docs/api-doc.json
          git commit -m "Update swagger.json"
          git push origin ${{ env.SOURCE_BRANCH }}

          curl -X POST \
            -H "Authorization: token ${{ env.PERSONAL_ACCESS_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ env.TARGET_REPO }}/pulls \
            -d '{
              "title": "Update Swagger JSON",
              "body": "Automatically generated Swagger JSON update\n\nGenerated by workflow run #${{ github.run_number }}",
              "head": "${{ env.SOURCE_BRANCH }}",
              "base": "${{ env.TARGET_BRANCH }}"
            }'
